### Logout and Invalidate Tokens
POST http://localhost:4009/logout
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ1c2VyQGV4YW1wbGUxLmNvbSIsInJvbGVzIjpbIlJPTEVfVVNFUiJdLCJpYXQiOjE3NTE3MDg2ODEsImV4cCI6MTc1MTcxMjI4MX0.FR28YOUdkQz0J7YQ_w2HYoJG7QsuDiP4CBmCP-Sv5ZH_wGSw3N7om86iP4_ELQ1X_fbfq_XplHOblMouP08eeA
Cookie: JWT_REFRESH_TOKEN=eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ1c2VyQGV4YW1wbGUxLmNvbSIsInJvbGVzIjpbIlJPTEVfVVNFUiJdLCJpYXQiOjE3NTE3MDg2ODEsImV4cCI6MTc1MjMxMzQ4MX0.0GopBQMDO9VD1mkcTQiHRXxyQ5ozXRJqFx-E_HTNnCxkQ0gkKtLCTXfG0pZcQutqQ2fCL6p8jYvuIgomUUh0sQ
