### Refresh Access Token using Refresh Token Cookie
POST http://localhost:4009/api/auth/refresh
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ1c2VyQGV4YW1wbGUxLmNvbSIsInJvbGVzIjpbIlJPTEVfVVNFUiJdLCJpYXQiOjE3NTE3MDg1NjcsImV4cCI6MTc1MTcxMjE2N30.NA8JM_0Z3TK2eWaiZYHcbbEMJklLFkWGwBTM6QcQaSEEF8jU_ejmwGKMNnD8TNyo_eMJulp9wmdUOSPVPmmMFA


Cookie: JWT_REFRESH_TOKEN=eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ1c2VyQGV4YW1wbGUxLmNvbSIsInJvbGVzIjpbIlJPTEVfVVNFUiJdLCJpYXQiOjE3NTE3MDc5MTIsImV4cCI6MTc1MjMxMjcxMn0.XdFCKvL0YBR3PZO3AX2oECwSb7AYNi71Bq9FmHTitzXBcBZjxqgMC0XNg-5dDv0is56-vyX3zT3Ii2aGRLZ5mQ
